const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Plugins.Particles,
		C3.Behaviors.EightDir,
		C3.Behaviors.bound,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.NinePatch,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.X,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.ScriptsInEvents.WordGameSheet_Event13_Act4,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ToggleBoolVar
	];
};
self.C3_JsPropNameTable = [
	{FrameToLetter: 0},
	{FrameToValue: 0},
	{Audio: 0},
	{Touch: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Physics: 0},
	{LetterFish: 0},
	{Sine: 0},
	{Bullet: 0},
	{Fish: 0},
	{BubbleParticle: 0},
	{BubbleParticle2: 0},
	{"8Direction": 0},
	{BoundToLayout: 0},
	{Hook: 0},
	{Line: 0},
	{UIBackground: 0},
	{Solid: 0},
	{Destroyer: 0},
	{Clock: 0},
	{LettersCaught: 0},
	{Locked: 0},
	{InitialX: 0},
	{InitialY: 0},
	{DragDrop: 0},
	{Letter: 0},
	{ID: 0},
	{LandingPad: 0},
	{ConstructingWord: 0},
	{Link: 0},
	{HelperText: 0},
	{SubmitWordButton: 0},
	{FoundWords: 0},
	{StatusText: 0},
	{Button: 0},
	{FinishGameText: 0},
	{menuList: 0},
	{CastArea: 0},
	{checkmark: 0},
	{LETTER_SPAWN_FREQUENCY: 0},
	{LETTER_SPAWN_RANGE: 0},
	{IsHookDown: 0},
	{ConstructedWord: 0},
	{WordIsCorrect: 0},
	{WordValue: 0},
	{MoveToIndex: 0},
	{LetterFrame: 0},
	{XPosition: 0},
	{YPosition: 0},
	{SecondsRemaining: 0},
	{TotalScore: 0},
	{HighScore: 0},
	{IsSoundOn: 0}
];

self.InstanceType = {
	FrameToLetter: class extends self.IArrayInstance {},
	FrameToValue: class extends self.IArrayInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LetterFish: class extends self.ISpriteInstance {},
	Fish: class extends self.ISpriteInstance {},
	BubbleParticle: class extends self.IParticlesInstance {},
	BubbleParticle2: class extends self.IParticlesInstance {},
	Hook: class extends self.ISpriteInstance {},
	Line: class extends self.ISpriteInstance {},
	UIBackground: class extends self.ITiledBackgroundInstance {},
	Destroyer: class extends self.ISpriteInstance {},
	Clock: class extends self.ITextInstance {},
	LettersCaught: class extends self.IArrayInstance {},
	Letter: class extends self.ISpriteInstance {},
	LandingPad: class extends self.ISpriteInstance {},
	ConstructingWord: class extends self.IArrayInstance {},
	HelperText: class extends self.ITextInstance {},
	SubmitWordButton: class extends self.IWorldInstance {},
	FoundWords: class extends self.IArrayInstance {},
	StatusText: class extends self.ITextInstance {},
	Button: class extends self.IWorldInstance {},
	FinishGameText: class extends self.ITextInstance {},
	menuList: class extends self.ISpriteInstance {},
	CastArea: class extends self.ITiledBackgroundInstance {},
	checkmark: class extends self.ISpriteInstance {}
}